/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_androgames_level_Linuxc */
#ifndef _Included_net_androgames_level_Linuxc
#define _Included_net_androgames_level_Linuxc
#define SENSOR_DATA_SIZE 3
#define IOCTL_MAGIC  0x09                         

#define SENSOR_RESET    		_IO(IOCTL_MAGIC, 0)
#define SENSOR_CALIBRATION   	_IOWR(IOCTL_MAGIC,  1, int[SENSOR_DATA_SIZE])
#define SENSOR_GET_OFFSET  		_IOR(IOCTL_MAGIC,  2, int[SENSOR_DATA_SIZE])
#define SENSOR_SET_OFFSET  		_IOWR(IOCTL_MAGIC,  3, int[SENSOR_DATA_SIZE])
#define SENSOR_READ_ACCEL_XYZ  	_IOR(IOCTL_MAGIC,  4, int[SENSOR_DATA_SIZE])
#define SENSOR_SETYPR  			_IOW(IOCTL_MAGIC,  5, int[SENSOR_DATA_SIZE])
#define SENSOR_GET_OPEN_STATUS	_IO(IOCTL_MAGIC,  6)
#define SENSOR_GET_CLOSE_STATUS	_IO(IOCTL_MAGIC,  7)
#define SENSOR_GET_DELAY		_IOR(IOCTL_MAGIC,  8, unsigned int*)

#define SENSOR_MAXNR 8

#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jint JNICALL Java_net_androgames_level_Linuxc_open
  (JNIEnv *, jclass);
JNIEXPORT jint JNICALL Java_net_androgames_level_Linuxc_close
  (JNIEnv *, jclass);
JNIEXPORT jint JNICALL Java_net_androgames_level_Linuxc_reset
  (JNIEnv *, jclass);
JNIEXPORT jint JNICALL Java_net_androgames_level_Linuxc_cab
  (JNIEnv *, jclass, jintArray);
JNIEXPORT jint JNICALL Java_net_androgames_level_Linuxc_getoffset
  (JNIEnv *, jclass, jintArray);
JNIEXPORT jint JNICALL Java_net_androgames_level_Linuxc_setoffset
  (JNIEnv *, jclass, jintArray);
JNIEXPORT jint JNICALL Java_net_androgames_level_Linuxc_readxyz
  (JNIEnv *, jclass, jintArray);
  
#ifdef __cplusplus
}
#endif
#endif
